; generated by PrusaSlicer 2.9.0 on 2025-03-07 at 08:15:33 UTC

; 

; external perimeters extrusion width = 10.00mm
; perimeters extrusion width = 10.00mm
; infill extrusion width = 10.00mm
; solid infill extrusion width = 10.00mm
; top infill extrusion width = 10.00mm
; first layer extrusion width = 10.00mm

;TYPE:Custom
CLEAR PAUSE
M83
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:7
;HEIGHT:7
G1 E-100 F3600
G1 Z7 F6000
G1 X29.206 Y103.004
G1 Z7
G1 E100 F2400
;TYPE:Skirt/Brim
;WIDTH:10
G1 F300
G1 X35 Y102.253 E288.97766
G1 X235 Y102.253 E9892.31393
G1 X239.242 Y102.652 E210.74207
G1 X243.336 Y103.836 E210.79388
G1 X247.137 Y105.762 E210.7613
G1 X250.512 Y108.363 E210.75404
G1 X253.343 Y111.548 E210.77122
G1 X255.53 Y115.205 E210.75863
G1 X256.996 Y119.206 E210.76176
G1 X257.747 Y125 E288.97766
G1 X257.747 Y145 E989.23139
G1 X257.348 Y149.242 E210.74207
G1 X256.164 Y153.336 E210.79388
G1 X254.238 Y157.137 E210.7613
G1 X251.637 Y160.512 E210.75404
G1 X248.452 Y163.343 E210.77122
G1 X244.795 Y165.53 E210.75863
G1 X240.794 Y166.996 E210.76176
G1 X235 Y167.747 E288.97766
G1 X35 Y167.747 E9892.31393
G1 X30.758 Y167.348 E210.74207
G1 X26.664 Y166.164 E210.79388
G1 X22.863 Y164.238 E210.7613
G1 X19.488 Y161.637 E210.75404
G1 X16.657 Y158.452 E210.77122
G1 X14.47 Y154.795 E210.75863
G1 X13.004 Y150.794 E210.76176
G1 X12.253 Y145 E288.97766
G1 X12.253 Y125 E989.23139
G1 X12.652 Y120.758 E210.74207
G1 X13.836 Y116.664 E210.79388
G1 X15.762 Y112.863 E210.7613
G1 X18.363 Y109.488 E210.75404
G1 X21.548 Y106.657 E210.77122
G1 X25.205 Y104.47 E210.75863
G1 X27.798 Y103.52 E136.59051
G1 E-70 F3600
;WIPE_START
G1 F4800
G1 X29.206 Y103.004 E-1.06845
G1 X35 Y102.253 E-4.16276
G1 X69.763 Y102.253 E-24.76879
;WIPE_END
G1 X30.031 Y111.69 F6000
G1 E100 F2400
G1 F300
G1 X32.895 Y110.907 E146.8566
G1 X35 Y110.751 E104.40213
G1 X235 Y110.751 E9892.31393
G1 X238.347 Y111.15 E166.72005
G1 X241.506 Y112.323 E166.67309
G1 X244.302 Y114.206 E166.73249
G1 X246.577 Y116.693 E166.71406
G1 X248.204 Y119.644 E166.67544
G1 X249.093 Y122.895 E166.70326
G1 X249.249 Y125 E104.40213
G1 X249.249 Y145 E989.23139
G1 X248.85 Y148.347 E166.72005
G1 X247.677 Y151.506 E166.67309
G1 X245.794 Y154.302 E166.73249
G1 X243.307 Y156.577 E166.71406
G1 X240.356 Y158.204 E166.67544
G1 X237.105 Y159.093 E166.70326
G1 X235 Y159.249 E104.40213
G1 X35 Y159.249 E9892.31393
G1 X31.653 Y158.85 E166.72005
G1 X28.494 Y157.677 E166.67309
G1 X25.698 Y155.794 E166.73249
G1 X23.423 Y153.307 E166.71406
G1 X21.796 Y150.356 E166.67544
G1 X20.907 Y147.105 E166.70326
G1 X20.751 Y145 E104.40213
G1 X20.751 Y125 E989.23139
G1 X21.15 Y121.653 E166.72005
G1 X22.323 Y118.494 E166.67309
G1 X24.206 Y115.698 E166.73249
G1 X26.693 Y113.423 E166.71406
G1 X28.682 Y112.327 E112.32609
G1 E-70 F3600
;WIPE_START
G1 F4800
G1 X30.031 Y111.69 E-1.06293
G1 X32.895 Y110.907 E-2.11549
G1 X35 Y110.751 E-1.50393
G1 X70.534 Y110.751 E-25.31765
;WIPE_END
G1 X40 Y130 F6000
G1 E100 F2400
;TYPE:External perimeter
G1 F300
G1 X230 Y130 E9397.69824
G1 X230 Y140 E494.6157
G1 X40 Y140 E9397.69824
G1 X40 Y131.5 E420.42334
;LAYER_CHANGE
;Z:14
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;14


G1 Z7.000 F6000
;AFTER_LAYER_CHANGE
;14
G1 F300
G1 Z7.026 X40 Y130 E0.27822
G1 Z10.351 X230 Y130 E4499.14795
G1 Z10.526 X230 Y140 E249.16267
G1 Z13.851 X40 Y140 E9197.99707
G1 Z14.000 X40 Y131.5 E420.42334
;LAYER_CHANGE
;Z:21
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;21


G1 Z14.000 F6000
;AFTER_LAYER_CHANGE
;21
G1 F300
G1 Z14.026 X40.000 Y130.000 E74.19235
G1 Z17.351 X230.000 Y130.000 E9397.69824
G1 Z17.526 X230.000 Y140.000 E494.61566
G1 Z20.851 X40.000 Y140.000 E9397.69824
G1 Z21.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:28
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;28


G1 Z21.000 F6000
;AFTER_LAYER_CHANGE
;28
G1 F300
G1 Z21.026 X40.000 Y130.000 E74.19235
G1 Z24.351 X230.000 Y130.000 E9397.69824
G1 Z24.526 X230.000 Y140.000 E494.61566
G1 Z27.851 X40.000 Y140.000 E9397.69824
G1 Z28.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:35
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;35


G1 Z28.000 F6000
;AFTER_LAYER_CHANGE
;35
G1 F300
G1 Z28.026 X40.000 Y130.000 E74.19235
G1 Z31.351 X230.000 Y130.000 E9397.69824
G1 Z31.526 X230.000 Y140.000 E494.61566
G1 Z34.851 X40.000 Y140.000 E9397.69824
G1 Z35.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:42
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;42


G1 Z35.000 F6000
;AFTER_LAYER_CHANGE
;42
G1 F300
G1 Z35.026 X40.000 Y130.000 E74.19235
G1 Z38.351 X230.000 Y130.000 E9397.69824
G1 Z38.526 X230.000 Y140.000 E494.61566
G1 Z41.851 X40.000 Y140.000 E9397.69824
G1 Z42.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:49
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;49


G1 Z42.000 F6000
;AFTER_LAYER_CHANGE
;49
G1 F300
G1 Z42.026 X40.000 Y130.000 E74.19235
G1 Z45.351 X230.000 Y130.000 E9397.69824
G1 Z45.526 X230.000 Y140.000 E494.61566
G1 Z48.851 X40.000 Y140.000 E9397.69824
G1 Z49.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:56
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;56


G1 Z49.000 F6000
;AFTER_LAYER_CHANGE
;56
G1 F300
G1 Z49.026 X40.000 Y130.000 E74.19235
G1 Z52.351 X230.000 Y130.000 E9397.69824
G1 Z52.526 X230.000 Y140.000 E494.61566
G1 Z55.851 X40.000 Y140.000 E9397.69824
G1 Z56.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:63
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;63


G1 Z56.000 F6000
;AFTER_LAYER_CHANGE
;63
G1 F300
G1 Z56.026 X40.000 Y130.000 E74.19235
G1 Z59.351 X230.000 Y130.000 E9397.69824
G1 Z59.526 X230.000 Y140.000 E494.61566
G1 Z62.851 X40.000 Y140.000 E9397.69824
G1 Z63.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:70
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;70


G1 Z63.000 F6000
;AFTER_LAYER_CHANGE
;70
G1 F300
G1 Z63.026 X40.000 Y130.000 E74.19235
G1 Z66.351 X230.000 Y130.000 E9397.69824
G1 Z66.526 X230.000 Y140.000 E494.61566
G1 Z69.851 X40.000 Y140.000 E9397.69824
G1 Z70.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:77
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;77


G1 Z70.000 F6000
;AFTER_LAYER_CHANGE
;77
G1 F300
G1 Z70.026 X40.000 Y130.000 E74.19235
G1 Z73.351 X230.000 Y130.000 E9397.69824
G1 Z73.526 X230.000 Y140.000 E494.61566
G1 Z76.851 X40.000 Y140.000 E9397.69824
G1 Z77.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:84
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;84


G1 Z77.000 F6000
;AFTER_LAYER_CHANGE
;84
G1 F300
G1 Z77.026 X40.000 Y130.000 E74.19235
G1 Z80.351 X230.000 Y130.000 E9397.69824
G1 Z80.526 X230.000 Y140.000 E494.61566
G1 Z83.851 X40.000 Y140.000 E9397.69824
G1 Z84.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:91
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;91


G1 Z84.000 F6000
;AFTER_LAYER_CHANGE
;91
G1 F300
G1 Z84.026 X40.000 Y130.000 E74.19235
G1 Z87.351 X230.000 Y130.000 E9397.69824
G1 Z87.526 X230.000 Y140.000 E494.61566
G1 Z90.851 X40.000 Y140.000 E9397.69824
G1 Z91.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:98
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;98


G1 Z91.000 F6000
;AFTER_LAYER_CHANGE
;98
G1 F300
G1 Z91.026 X40.000 Y130.000 E74.19235
G1 Z94.351 X230.000 Y130.000 E9397.69824
G1 Z94.526 X230.000 Y140.000 E494.61566
G1 Z97.851 X40.000 Y140.000 E9397.69824
G1 Z98.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:105
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;105


G1 Z98.000 F6000
;AFTER_LAYER_CHANGE
;105
G1 F300
G1 Z98.026 X40.000 Y130.000 E74.19235
G1 Z101.351 X230.000 Y130.000 E9397.69824
G1 Z101.526 X230.000 Y140.000 E494.61566
G1 Z104.851 X40.000 Y140.000 E9397.69824
G1 Z105.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:112
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;112


G1 Z105.000 F6000
;AFTER_LAYER_CHANGE
;112
G1 F300
G1 Z105.026 X40.000 Y130.000 E74.19235
G1 Z108.351 X230.000 Y130.000 E9397.69824
G1 Z108.526 X230.000 Y140.000 E494.61566
G1 Z111.851 X40.000 Y140.000 E9397.69824
G1 Z112.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:119
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;119


G1 Z112.000 F6000
;AFTER_LAYER_CHANGE
;119
G1 F300
G1 Z112.026 X40.000 Y130.000 E74.19235
G1 Z115.351 X230.000 Y130.000 E9397.69824
G1 Z115.526 X230.000 Y140.000 E494.61566
G1 Z118.851 X40.000 Y140.000 E9397.69824
G1 Z119.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:126
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;126


G1 Z119.000 F6000
;AFTER_LAYER_CHANGE
;126
G1 F300
G1 Z119.026 X40.000 Y130.000 E74.19235
G1 Z122.351 X230.000 Y130.000 E9397.69824
G1 Z122.526 X230.000 Y140.000 E494.61566
G1 Z125.851 X40.000 Y140.000 E9397.69824
G1 Z126.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:133
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;133


G1 Z126.000 F6000
;AFTER_LAYER_CHANGE
;133
G1 F300
G1 Z126.026 X40.000 Y130.000 E74.19235
G1 Z129.351 X230.000 Y130.000 E9397.69824
G1 Z129.526 X230.000 Y140.000 E494.61566
G1 Z132.851 X40.000 Y140.000 E9397.69824
G1 Z133.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:140
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;140


G1 Z133.000 F6000
;AFTER_LAYER_CHANGE
;140
G1 F300
G1 Z133.026 X40.000 Y130.000 E74.19235
G1 Z136.351 X230.000 Y130.000 E9397.69824
G1 Z136.526 X230.000 Y140.000 E494.61566
G1 Z139.851 X40.000 Y140.000 E9397.69824
G1 Z140.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:147
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;147


G1 Z140.000 F6000
;AFTER_LAYER_CHANGE
;147
G1 F300
G1 Z140.026 X40.000 Y130.000 E74.19235
G1 Z143.351 X230.000 Y130.000 E9397.69824
G1 Z143.526 X230.000 Y140.000 E494.61566
G1 Z146.851 X40.000 Y140.000 E9397.69824
G1 Z147.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:154
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;154


G1 Z147.000 F6000
;AFTER_LAYER_CHANGE
;154
G1 F300
G1 Z147.026 X40.000 Y130.000 E74.19235
G1 Z150.351 X230.000 Y130.000 E9397.69824
G1 Z150.526 X230.000 Y140.000 E494.61566
G1 Z153.851 X40.000 Y140.000 E9397.69824
G1 Z154.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:161
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;161


G1 Z154.000 F6000
;AFTER_LAYER_CHANGE
;161
G1 F300
G1 Z154.026 X40.000 Y130.000 E74.19235
G1 Z157.351 X230.000 Y130.000 E9397.69824
G1 Z157.526 X230.000 Y140.000 E494.61566
G1 Z160.851 X40.000 Y140.000 E9397.69824
G1 Z161.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:168
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;168


G1 Z161.000 F6000
;AFTER_LAYER_CHANGE
;168
G1 F300
G1 Z161.026 X40.000 Y130.000 E74.19235
G1 Z164.351 X230.000 Y130.000 E9397.69824
G1 Z164.526 X230.000 Y140.000 E494.61566
G1 Z167.851 X40.000 Y140.000 E9397.69824
G1 Z168.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:175
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;175


G1 Z168.000 F6000
;AFTER_LAYER_CHANGE
;175
G1 F300
G1 Z168.026 X40.000 Y130.000 E74.19235
G1 Z171.351 X230.000 Y130.000 E9397.69824
G1 Z171.526 X230.000 Y140.000 E494.61566
G1 Z174.851 X40.000 Y140.000 E9397.69824
G1 Z175.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:182
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;182


G1 Z175.000 F6000
;AFTER_LAYER_CHANGE
;182
G1 F300
G1 Z175.026 X40.000 Y130.000 E74.19235
G1 Z178.351 X230.000 Y130.000 E9397.69824
G1 Z178.526 X230.000 Y140.000 E494.61566
G1 Z181.851 X40.000 Y140.000 E9397.69824
G1 Z182.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:189
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;189


G1 Z182.000 F6000
;AFTER_LAYER_CHANGE
;189
G1 F300
G1 Z182.026 X40.000 Y130.000 E74.19235
G1 Z185.351 X230.000 Y130.000 E9397.69824
G1 Z185.526 X230.000 Y140.000 E494.61566
G1 Z188.851 X40.000 Y140.000 E9397.69824
G1 Z189.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:196
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;196


G1 Z189.000 F6000
;AFTER_LAYER_CHANGE
;196
G1 F300
G1 Z189.026 X40.000 Y130.000 E74.19235
G1 Z192.351 X230.000 Y130.000 E9397.69824
G1 Z192.526 X230.000 Y140.000 E494.61566
G1 Z195.851 X40.000 Y140.000 E9397.69824
G1 Z196.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:203
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;203


G1 Z196.000 F6000
;AFTER_LAYER_CHANGE
;203
G1 F300
G1 Z196.026 X40.000 Y130.000 E74.19235
G1 Z199.351 X230.000 Y130.000 E9397.69824
G1 Z199.526 X230.000 Y140.000 E494.61566
G1 Z202.851 X40.000 Y140.000 E9397.69824
G1 Z203.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:210
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;210


G1 Z203.000 F6000
;AFTER_LAYER_CHANGE
;210
G1 F300
G1 Z203.026 X40.000 Y130.000 E74.19235
G1 Z206.351 X230.000 Y130.000 E9397.69824
G1 Z206.526 X230.000 Y140.000 E494.61566
G1 Z209.851 X40.000 Y140.000 E9397.69824
G1 Z210.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:217
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;217


G1 Z210.000 F6000
;AFTER_LAYER_CHANGE
;217
G1 F300
G1 Z210.026 X40.000 Y130.000 E74.19235
G1 Z213.351 X230.000 Y130.000 E9397.69824
G1 Z213.526 X230.000 Y140.000 E494.61566
G1 Z216.851 X40.000 Y140.000 E9397.69824
G1 Z217.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:224
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;224


G1 Z217.000 F6000
;AFTER_LAYER_CHANGE
;224
G1 F300
G1 Z217.026 X40.000 Y130.000 E74.19235
G1 Z220.351 X230.000 Y130.000 E9397.69824
G1 Z220.526 X230.000 Y140.000 E494.61566
G1 Z223.851 X40.000 Y140.000 E9397.69824
G1 Z224.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:231
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;231


G1 Z224.000 F6000
;AFTER_LAYER_CHANGE
;231
G1 F300
G1 Z224.026 X40.000 Y130.000 E74.19235
G1 Z227.351 X230.000 Y130.000 E9397.69824
G1 Z227.526 X230.000 Y140.000 E494.61566
G1 Z230.851 X40.000 Y140.000 E9397.69824
G1 Z231.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:238
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;238


G1 Z231.000 F6000
;AFTER_LAYER_CHANGE
;238
G1 F300
G1 Z231.026 X40.000 Y130.000 E74.19235
G1 Z234.351 X230.000 Y130.000 E9397.69824
G1 Z234.526 X230.000 Y140.000 E494.61566
G1 Z237.851 X40.000 Y140.000 E9397.69824
G1 Z238.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:245
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;245


G1 Z238.000 F6000
;AFTER_LAYER_CHANGE
;245
G1 F300
G1 Z238.026 X40.000 Y130.000 E74.19235
G1 Z241.351 X230.000 Y130.000 E9397.69824
G1 Z241.526 X230.000 Y140.000 E494.61566
G1 Z244.851 X40.000 Y140.000 E9397.69824
G1 Z245.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:252
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;252


G1 Z245.000 F6000
;AFTER_LAYER_CHANGE
;252
G1 F300
G1 Z245.026 X40.000 Y130.000 E74.19235
G1 Z248.351 X230.000 Y130.000 E9397.69824
G1 Z248.526 X230.000 Y140.000 E494.61566
G1 Z251.851 X40.000 Y140.000 E9397.69824
G1 Z252.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:259
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;259


G1 Z252.000 F6000
;AFTER_LAYER_CHANGE
;259
G1 F300
G1 Z252.026 X40.000 Y130.000 E74.19235
G1 Z255.351 X230.000 Y130.000 E9397.69824
G1 Z255.526 X230.000 Y140.000 E494.61566
G1 Z258.851 X40.000 Y140.000 E9397.69824
G1 Z259.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:266
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;266


G1 Z259.000 F6000
;AFTER_LAYER_CHANGE
;266
G1 F300
G1 Z259.026 X40.000 Y130.000 E74.19235
G1 Z262.351 X230.000 Y130.000 E9397.69824
G1 Z262.526 X230.000 Y140.000 E494.61566
G1 Z265.851 X40.000 Y140.000 E9397.69824
G1 Z266.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:273
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;273


G1 Z266.000 F6000
;AFTER_LAYER_CHANGE
;273
G1 F300
G1 Z266.026 X40.000 Y130.000 E74.19235
G1 Z269.351 X230.000 Y130.000 E9397.69824
G1 Z269.526 X230.000 Y140.000 E494.61566
G1 Z272.851 X40.000 Y140.000 E9397.69824
G1 Z273.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:280
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;280


G1 Z273.000 F6000
;AFTER_LAYER_CHANGE
;280
G1 F300
G1 Z273.026 X40.000 Y130.000 E74.19235
G1 Z276.351 X230.000 Y130.000 E9397.69824
G1 Z276.526 X230.000 Y140.000 E494.61566
G1 Z279.851 X40.000 Y140.000 E9397.69824
G1 Z280.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:287
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;287


G1 Z280.000 F6000
;AFTER_LAYER_CHANGE
;287
G1 F300
G1 Z280.026 X40.000 Y130.000 E74.19235
G1 Z283.351 X230.000 Y130.000 E9397.69824
G1 Z283.526 X230.000 Y140.000 E494.61566
G1 Z286.851 X40.000 Y140.000 E9397.69824
G1 Z287.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:294
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;294


G1 Z287.000 F6000
;AFTER_LAYER_CHANGE
;294
G1 F300
G1 Z287.026 X40.000 Y130.000 E74.19235
G1 Z290.351 X230.000 Y130.000 E9397.69824
G1 Z290.526 X230.000 Y140.000 E494.61566
G1 Z293.851 X40.000 Y140.000 E9397.69824
G1 Z294.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:301
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;301


G1 Z294.000 F6000
;AFTER_LAYER_CHANGE
;301
G1 F300
G1 Z294.026 X40.000 Y130.000 E74.19235
G1 Z297.351 X230.000 Y130.000 E9397.69824
G1 Z297.526 X230.000 Y140.000 E494.61566
G1 Z300.851 X40.000 Y140.000 E9397.69824
G1 Z301.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:308
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;308


G1 Z301.000 F6000
;AFTER_LAYER_CHANGE
;308
G1 F300
G1 Z301.026 X40.000 Y130.000 E74.19235
G1 Z304.351 X230.000 Y130.000 E9397.69824
G1 Z304.526 X230.000 Y140.000 E494.61566
G1 Z307.851 X40.000 Y140.000 E9397.69824
G1 Z308.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:315
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;315


G1 Z308.000 F6000
;AFTER_LAYER_CHANGE
;315
G1 F300
G1 Z308.026 X40.000 Y130.000 E74.19235
G1 Z311.351 X230.000 Y130.000 E9397.69824
G1 Z311.526 X230.000 Y140.000 E494.61566
G1 Z314.851 X40.000 Y140.000 E9397.69824
G1 Z315.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:322
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;322


G1 Z315.000 F6000
;AFTER_LAYER_CHANGE
;322
G1 F300
G1 Z315.026 X40.000 Y130.000 E74.19235
G1 Z318.351 X230.000 Y130.000 E9397.69824
G1 Z318.526 X230.000 Y140.000 E494.61566
G1 Z321.851 X40.000 Y140.000 E9397.69824
G1 Z322.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:329
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;329


G1 Z322.000 F6000
;AFTER_LAYER_CHANGE
;329
G1 F300
G1 Z322.026 X40.000 Y130.000 E74.19235
G1 Z325.351 X230.000 Y130.000 E9397.69824
G1 Z325.526 X230.000 Y140.000 E494.61566
G1 Z328.851 X40.000 Y140.000 E9397.69824
G1 Z329.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:336
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;336


G1 Z329.000 F6000
;AFTER_LAYER_CHANGE
;336
G1 F300
G1 Z329.026 X40.000 Y130.000 E74.19235
G1 Z332.351 X230.000 Y130.000 E9397.69824
G1 Z332.526 X230.000 Y140.000 E494.61566
G1 Z335.851 X40.000 Y140.000 E9397.69824
G1 Z336.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:343
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;343


G1 Z336.000 F6000
;AFTER_LAYER_CHANGE
;343
G1 F300
G1 Z336.026 X40.000 Y130.000 E74.19235
G1 Z339.351 X230.000 Y130.000 E9397.69824
G1 Z339.526 X230.000 Y140.000 E494.61566
G1 Z342.851 X40.000 Y140.000 E9397.69824
G1 Z343.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:350
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;350


G1 Z343.000 F6000
;AFTER_LAYER_CHANGE
;350
G1 F300
G1 Z343.026 X40.000 Y130.000 E74.19235
G1 Z346.351 X230.000 Y130.000 E9397.69824
G1 Z346.526 X230.000 Y140.000 E494.61566
G1 Z349.851 X40.000 Y140.000 E9397.69824
G1 Z350.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:357
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;357


G1 Z350.000 F6000
;AFTER_LAYER_CHANGE
;357
G1 F300
G1 Z350.026 X40.000 Y130.000 E74.19235
G1 Z353.351 X230.000 Y130.000 E9397.69824
G1 Z353.526 X230.000 Y140.000 E494.61566
G1 Z356.851 X40.000 Y140.000 E9397.69824
G1 Z357.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:364
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;364


G1 Z357.000 F6000
;AFTER_LAYER_CHANGE
;364
G1 F300
G1 Z357.026 X40.000 Y130.000 E74.19235
G1 Z360.351 X230.000 Y130.000 E9397.69824
G1 Z360.526 X230.000 Y140.000 E494.61566
G1 Z363.851 X40.000 Y140.000 E9397.69824
G1 Z364.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:371
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;371


G1 Z364.000 F6000
;AFTER_LAYER_CHANGE
;371
G1 F300
G1 Z364.026 X40.000 Y130.000 E74.19235
G1 Z367.351 X230.000 Y130.000 E9397.69824
G1 Z367.526 X230.000 Y140.000 E494.61566
G1 Z370.851 X40.000 Y140.000 E9397.69824
G1 Z371.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:378
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;378


G1 Z371.000 F6000
;AFTER_LAYER_CHANGE
;378
G1 F300
G1 Z371.026 X40.000 Y130.000 E74.19235
G1 Z374.351 X230.000 Y130.000 E9397.69824
G1 Z374.526 X230.000 Y140.000 E494.61566
G1 Z377.851 X40.000 Y140.000 E9397.69824
G1 Z378.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:385
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;385


G1 Z378.000 F6000
;AFTER_LAYER_CHANGE
;385
G1 F300
G1 Z378.026 X40.000 Y130.000 E74.19235
G1 Z381.351 X230.000 Y130.000 E9397.69824
G1 Z381.526 X230.000 Y140.000 E494.61566
G1 Z384.851 X40.000 Y140.000 E9397.69824
G1 Z385.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:392
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;392


G1 Z385.000 F6000
;AFTER_LAYER_CHANGE
;392
G1 F300
G1 Z385.026 X40.000 Y130.000 E74.19235
G1 Z388.351 X230.000 Y130.000 E9397.69824
G1 Z388.526 X230.000 Y140.000 E494.61566
G1 Z391.851 X40.000 Y140.000 E9397.69824
G1 Z392.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:399
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;399


G1 Z392.000 F6000
;AFTER_LAYER_CHANGE
;399
G1 F300
G1 Z392.026 X40.000 Y130.000 E74.19235
G1 Z395.351 X230.000 Y130.000 E9397.69824
G1 Z395.526 X230.000 Y140.000 E494.61566
G1 Z398.851 X40.000 Y140.000 E9397.69824
G1 Z399.000 X40.000 Y131.500 E420.42334
;LAYER_CHANGE
;Z:399
;HEIGHT:7
;BEFORE_LAYER_CHANGE
G92 E0
;399


;AFTER_LAYER_CHANGE
;399
G1 X40 Y130 E73.91413
G1 X230 Y130 E4898.55029
G1 X230 Y140 E245.45302
G1 X40 Y140 E199.70117
G1 X40 Y131.5 E0.00000
G1 E-70 F3600
;WIPE_START
G1 F4800;_WIPE
G1 X40 Y130 E-1.06875
G1 X80.605 Y130 E-28.93125
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
;G1 Z400 F600 ; Move print head up
;G1 X5 Y229.5 F6000 ; present print
;
;
;M140 S0 ; turn off heatbed
;M104 S0 ; turn off temperature
;M107 ; turn off fan
;M84 X Y E ; disable motors
;G0 x10 y10 z250 E-5


CLEAR PAUSE
; objects_info = {"objects":[]}
; filament used [mm] = 1182503.27
; filament used [cm3] = 2844.25
; filament used [g] = 6826.21
; filament cost = 819.15
; total filament used [g] = 6826.21
; total filament cost = 819.15
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 5h 29m 23s
; estimated first layer printing time (normal mode) = 20m 58s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,270x0,270x270,0x270
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0\n;{layer_z}\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 1
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 0
; bridge_flow_ratio = 1
; bridge_speed = 5
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Generic PLA @CREALITY"
; default_print_profile = "0.16 mm OPTIMAL (0.4 mm nozzle) @CREALITY"
; deretract_speed = 40
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = ;{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\n;G1 X5 Y{print_bed_max[1]*0.85} F{travel_speed*60} ; present print\n;{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n;{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\n;M140 S0 ; turn off heatbed\n;M104 S0 ; turn off temperature\n;M107 ; turn off fan\n;M84 X Y E ; disable motors\n;G0 x10 y10 z250 E-5\n\n\nCLEAR PAUSE
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 10
; external_perimeter_speed = 5
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 2
; extrusion_width = 10
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 120
; filament_density = 2.4
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = 0
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "fdm4 concrete"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = FLEX
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; filament_wipe = nil
; fill_angle = 45
; fill_density = 0%
; fill_pattern = cubic
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 10
; first_layer_height = 7
; first_layer_speed = 5
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 5
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 10
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 5
; inherits_cummulative = ;;"Creality CR-10 S (0.4 mm nozzle)"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;{layer_z}
; layer_height = 7
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 500
; machine_max_acceleration_retracting = 1000
; machine_max_acceleration_travel = 500
; machine_max_acceleration_x = 500
; machine_max_acceleration_y = 500
; machine_max_acceleration_z = 100
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 10
; machine_max_jerk_e = 5
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 10
; max_print_height = 400
; max_print_speed = 50
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 1
; min_print_speed = 10
; min_skirt_length = 30
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 10
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = 
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 10
; perimeter_generator = classic
; perimeter_speed = 5
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = fdm4
; printer_model = CR10S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_CREALITY\nPRINTER_MODEL_CR10S\nPRINTER_HAS_BOWDEN
; printer_settings_id = fdm4
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 70%
; retract_layer_change = 0
; retract_length = 100
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0.2
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 60
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 10
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 5
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 10
; solid_infill_speed = 5
; spiral_vase = 1
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = \nCLEAR PAUSE\nM83
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 5
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 0
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 10
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 5
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 100
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
